modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]] 
modId="unusualfishmod" 
version="${file.jarVersion}"
displayName= "Unusual Fish Mod"
#logoFile= "examplemod.png"
#credits= ""
authors= "codyhuh (maintainer), OmayPaty (most art), Peeko32213 (former author)"
description='''
A mod that adds a variety of new aquatic creatures, both useful and atheistic!
'''

[[dependencies.unusualfishmod]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.unusualfishmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"